<?php
/**
 * Created by PhpStorm.
 * User: WLL
 * Date: 2018/3/14
 * Time: 19:26
 */

namespace app\admin\common;


use think\Controller;
use think\Session;

class Base extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        //在公共控制器的初始化方法中判断用户是否已登录
        define('USER_ID', Session::get('user_id'));
    }

    protected function isLogin ()
    {
        if (is_null(USER_ID)) {
            $this -> error('未登录，无权访问', 'login/index');
        }
    }

    protected function alreadyLogin ()
    {
        if (!is_null(USER_ID)) {
            $this -> error('请勿重复登录', 'index/index');
        }
    }
}